[package]
name = "milestone_escrow"
version = "1.0.0"
authors = []

[addresses]
escrow_addr = "0x9738830421e09f651a3c66afa6acf1c028a60a02dfbbfce348cf03c02fd04540"
milestone_escrow = "0x9738830421e09f651a3c66afa6acf1c028a60a02dfbbfce348cf03c02fd04540"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }

[dev-addresses]

[dev-dependencies]
