[package]
name = "milestone_escrow"
version = "1.0.0"
authors = []

[addresses]
escrow_addr = "0x3c6b0ded4b64efe9693eedab0e4a2b1dd073662bcecbd3b5a975370b5db644d0"
milestone_escrow = "0x3c6b0ded4b64efe9693eedab0e4a2b1dd073662bcecbd3b5a975370b5db644d0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }

[dev-addresses]

[dev-dependencies]
